---

- name: Generate secret for app_cas_secret_ticket_signing
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 512
    secret_gen_type: jwt_key
    secret_gen_name: app_cas_secret_ticket_signing
- name: Register app_cas_secret_ticket_signing
  ansible.builtin.set_fact:
    app_cas_secret_ticket_signing: '{{ secret_gen_value }}'

- name: Generate secret for app_cas_secret_ticket_encryption
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 16
    secret_gen_type: data_base64
    secret_gen_name: app_cas_secret_ticket_encryption
- name: Register app_cas_secret_ticket_encryption
  ansible.builtin.set_fact:
    app_cas_secret_ticket_encryption: '{{ secret_gen_value }}'

- name: Generate secret for app_cas_secret_tgc_signing
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 512
    secret_gen_type: jwt_key
    secret_gen_name: app_cas_secret_tgc_signing
- name: Register app_cas_secret_tgc_signing
  ansible.builtin.set_fact:
    app_cas_secret_tgc_signing: '{{ secret_gen_value }}'

- name: Generate secret for app_cas_secret_tgc_encryption
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 512
    secret_gen_type: jwt_key
    secret_gen_name: app_cas_secret_tgc_encryption
- name: Register app_cas_secret_tgc_encryption
  ansible.builtin.set_fact:
    app_cas_secret_tgc_encryption: '{{ secret_gen_value }}'

- name: Generate secret for app_cas_secret_webflow_signing
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 512
    secret_gen_type: jwt_key
    secret_gen_name: app_cas_secret_webflow_signing
- name: Register app_cas_secret_webflow_signing
  ansible.builtin.set_fact:
    app_cas_secret_webflow_signing: '{{ secret_gen_value }}'

- name: Generate secret for app_cas_secret_webflow_encryption
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 16
    secret_gen_type: data_base64
    secret_gen_name: app_cas_secret_webflow_encryption
- name: Register app_cas_secret_webflow_encryption
  ansible.builtin.set_fact:
    app_cas_secret_webflow_encryption: '{{ secret_gen_value }}'

- name: Generate secret for app_cas_secret_oauth_signing
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 512
    secret_gen_type: jwt_key
    secret_gen_name: app_cas_secret_oauth_signing
- name: Register app_cas_secret_oauth_signing
  ansible.builtin.set_fact:
    app_cas_secret_oauth_signing: '{{ secret_gen_value }}'

- name: Generate secret for app_cas_secret_oauth_encryption
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 256
    secret_gen_type: jwt_key
    secret_gen_name: app_cas_secret_oauth_encryption
- name: Register app_cas_secret_oauth_encryption
  ansible.builtin.set_fact:
    app_cas_secret_oauth_encryption: '{{ secret_gen_value }}'

- name: Generate secret for app_cas_secret_access_signing
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 512
    secret_gen_type: jwt_key
    secret_gen_name: app_cas_secret_access_signing
- name: Register app_cas_secret_access_signing
  ansible.builtin.set_fact:
    app_cas_secret_access_signing: '{{ secret_gen_value }}'

- name: Generate secret for app_cas_secret_access_encryption
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 256
    secret_gen_type: jwt_key
    secret_gen_name: app_cas_secret_access_encryption
- name: Register app_cas_secret_access_encryption
  ansible.builtin.set_fact:
    app_cas_secret_access_encryption: '{{ secret_gen_value }}'

- name: Generate secret for app_cas_secret_token_signing
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 512
    secret_gen_type: jwt_key
    secret_gen_name: app_cas_secret_token_signing
- name: Register app_cas_secret_token_signing
  ansible.builtin.set_fact:
    app_cas_secret_token_signing: '{{ secret_gen_value }}'

- name: Generate secret for app_cas_secret_token_encryption
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 256
    secret_gen_type: jwt_key
    secret_gen_name: app_cas_secret_token_encryption
- name: Register app_cas_secret_token_encryption
  ansible.builtin.set_fact:
    app_cas_secret_token_encryption: '{{ secret_gen_value }}'

- name: Generate secret for app_cas_mysql_db_main_password
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 30
    secret_gen_type: password_string
    secret_gen_name: app_cas_mysql_db_main_password
- name: Register app_cas_mysql_db_main_password
  ansible.builtin.set_fact:
    app_cas_mysql_db_main_password: '{{ secret_gen_value }}'

- name: Generate secret for app_cas_mysql_db_test_password
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 30
    secret_gen_type: password_string
    secret_gen_name: app_cas_mysql_db_test_password
- name: Register app_cas_mysql_db_test_password
  ansible.builtin.set_fact:
    app_cas_mysql_db_test_password: '{{ secret_gen_value }}'

- name: Generate secret for app_cas_ala_user_create_password
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 30
    secret_gen_type: password_string
    secret_gen_name: app_cas_ala_user_create_password
- name: Register app_cas_ala_user_create_password
  ansible.builtin.set_fact:
    app_cas_ala_user_create_password: '{{ secret_gen_value }}'

- name: Generate secret for app_cas_mongo_db_spring_data_password
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 30
    secret_gen_type: password_string
    secret_gen_name: app_cas_mongo_db_spring_data_password
- name: Register app_cas_mongo_db_spring_data_password
  ansible.builtin.set_fact:
    app_cas_mongo_db_spring_data_password: '{{ secret_gen_value }}'

- name: Generate secret for app_cas_spring_security_password
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 30
    secret_gen_type: password_string
    secret_gen_name: app_cas_spring_security_password
- name: Register app_cas_spring_security_password
  ansible.builtin.set_fact:
    app_cas_spring_security_password: '{{ secret_gen_value }}'

- name: Generate secret for app_cas_mongo_db_main_password
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 30
    secret_gen_type: password_string
    secret_gen_name: app_cas_mongo_db_main_password
- name: Register app_cas_mongo_db_main_password
  ansible.builtin.set_fact:
    app_cas_mongo_db_main_password: '{{ secret_gen_value }}'

- name: Generate secret for app_cas_pwe_secret
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 128
    secret_gen_type: password_string
    secret_gen_name: app_cas_pwe_secret
- name: Register app_cas_pwe_secret
  ansible.builtin.set_fact:
    app_cas_pwe_secret: '{{ secret_gen_value }}'
