---

# --- Set secrets ---

- name: Generate secret for objectstore_service_password
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 30
    secret_gen_type: password_string
    secret_gen_name: objectstore_service_password

- name: Register objectstore_service_password
  ansible.builtin.set_fact:
    objectstore_service_password: '{{ secret_gen_value }}'

- name: Generate secret for mongo_service_root_password
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 30
    secret_gen_type: password_string
    secret_gen_name: mongo_service_root_password

- name: Register mongo_service_root_password
  ansible.builtin.set_fact:
    mongo_service_root_password: '{{ secret_gen_value }}'

- name: Generate secret for mongo_ui_service_site_cookie_secret
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 30
    secret_gen_type: password_string
    secret_gen_name: mongo_ui_service_site_cookie_secret

- name: Register mongo_ui_service_site_cookie_secret
  ansible.builtin.set_fact:
    mongo_ui_service_site_cookie_secret: '{{ secret_gen_value }}'

- name: Generate secret for mongo_ui_service_site_session_secret
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 30
    secret_gen_type: password_string
    secret_gen_name: mongo_ui_service_site_session_secret

- name: Register mongo_ui_service_site_session_secret
  ansible.builtin.set_fact:
    mongo_ui_service_site_session_secret: '{{ secret_gen_value }}'

- name: Generate secret for mysql_service_root_password
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 30
    secret_gen_type: password_string
    secret_gen_name: mysql_service_root_password

- name: Register mysql_service_root_password
  ansible.builtin.set_fact:
    mysql_service_root_password: '{{ secret_gen_value }}'

- name: Generate secret for elasticsearch_service_root_password
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 30
    secret_gen_type: password_string
    secret_gen_name: elasticsearch_service_root_password

- name: Register elasticsearch_service_root_password
  ansible.builtin.set_fact:
    elasticsearch_service_root_password: '{{ secret_gen_value }}'
