---

# Examples:
# https://github.com/AtlasOfLivingAustralia/ala-install/tree/master/ansible/roles/cas5/templates
# https://github.com/AtlasOfLivingAustralia/ala-cas-5/blob/develop/etc/cas/config/application.yml
# https://github.com/AtlasOfLivingAustralia/ala-cas-5/blob/develop/src/main/resources/application.yml


{{ lookup("ansible.builtin.template", "shared-content.yml") }}

# --- Database ---

common_datasource_mysql_main_properties: &common_datasource_mysql_main_properties
  url: '{{ mysql_base_url }}/{{ app_cas_mysql_db_main_database }}?{{ mysql_default_uri_options }}'
  jdbcUrl: '{{ mysql_base_url }}/{{ app_cas_mysql_db_main_database }}?{{ mysql_default_uri_options }}'
  user: '{{ app_cas_mysql_db_main_username }}'
  password: '{{ app_cas_mysql_db_main_password }}'

common_spring_data_mongodb_properties: &common_spring_data_mongodb_properties
  uri: 'mongodb://{{ app_cas_db_spring_data_username }}:{{ app_cas_db_spring_data_password }}@{{ web_base_host }}:{{ specified_ports.mongo_service_port }}/{{ app_cas_db_spring_data_database }}?{{ mongo_default_uri_options }}'
  host: '{{ web_base_host }}'
  port: {{ specified_ports.mongo_service_port }}
  username: '{{ app_cas_db_spring_data_username }}'
  password: '{{ app_cas_db_spring_data_password }}'
  database: '{{ app_cas_db_spring_data_database }}'

# --- Basic settings ---

info:
  description: '[Org Name Short] [Proj Name Short] [{{ app_cas_name }}] [dev]'
logging:
  config: file:{{ guest_src_dir }}/ala-cas-5/src/main/resources/log4j2.xml

# --- Embedded web server ---

server:
  # The 'server.*' settings are for the embedded containers that ship with CAS.
  port: {{ specified_ports.cas_http_port }}
  forward-headers-strategy: native
  session:
    timeout: 86400
  ssl:
    enabled: false
    key-store: ''
  servlet:
    application-display-name: '[Org Name Short] [Proj Name Short] [{{ app_cas_name }}] [dev]'
    # NOTE: server.servlet.contextPath is appended to the nginx proxy_pass url, which might already have a trailing slash.
    # The slashes *cannot* be duplicated, so if the nginx proxy_pass has a trailing slash (which is significant to nginx),
    # this contextPath must not have a starting slash.
    # NOTE: CAS 6.x will fail if the context-path does not start with a slash.
    context-path: '/{{ app_cas_name }}'
    session:
      timeout: '8h'
  tomcat:
    accesslog:
      # see https://apereo.github.io/cas/6.5.x/installation/Configuring-Servlet-Container-Embedded-Tomcat.html#configuration
      enabled: true
    # see https://apereo.github.io/cas/6.5.x/installation/Configuring-Servlet-Container-Embedded-Tomcat.html#configuration
    # see https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#application-properties.server.server.tomcat.use-relative-redirects
    # Whether HTTP 1.1 and later location headers generated by a call to sendRedirect will use relative or absolute redirects.
    use-relative-redirects: false
    # see https://github.com/spring-projects/spring-boot/commit/28f7bc37a54f3705550a248be2bff67f5e788d2b
    # see https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto.webserver.use-behind-a-proxy-server
    # Whether requests to the context root should be redirected by appending a / to the path.
    # When using SSL terminated at a proxy, this property should be set to false.
    redirect-context-root: false
    remoteip:
      # see https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#application-properties.server.server.tomcat.remoteip.host-header
      host-header: X-Forwarded-Host
      protocol-header: x-forwarded-proto
      port-header: x-forwarded-port
      remote-ip-header: x-forwarded-for
      protocol-header-https-value: https

# --- CAS settings ---

cas:


# --- CAS ticket registry ---


# --- ALA settings ---

debug: false
supportEmail: '[Org Support Email]'

ala:
  userDetailsBaseUrl: '{{ web_base_url }}/{{ app_userdetails_name }}/'
  baseURL: '{{ web_base_url }}/{{ app_cas_name }}'
  userDetailsURL: '{{ web_base_url }}/{{ app_userdetails_name }}/userDetails/getUserListFull'
  supportEmail: '[Org Support Email]'

# --- ALA cookie settings ---

  cookie:
    domain: '{{ web_base_authority }}'
    httpOnly: true
    # maxAge of 86400 seconds is 1 day
    maxAge: 86400
    rememberMeMaxAge: 86400
    name: 'ALA-Auth'
    path: '/'
    secure: true
    sameSitePolicy: 'Lax'
    quoteValue: true
    urlEncodeValue: false

# --- ALA user creation settings ---

  userCreator:
    defaultCountry: 'AU'
    countriesListUrl: '{{ web_base_url }}/{{ app_userdetails_name }}/ws/registration/countries'
    statesListUrl: '{{ web_base_url }}/{{ app_userdetails_name }}/ws/registration/states'

    userCreatePassword: "{{ app_cas_ala_user_create_password }}"
    enableUserSurvey: false

    passwordEncoder:
      # This should be the same as the primary password encoder
      type: BCRYPT
      characterEncoding: UTF-8
      strength: 10
    jdbc:
      <<: *shared_datasource_mysql_defaults
      <<: *common_datasource_mysql_main_properties
      dataSourceName: 'java:comp/env/jdbccas'
      enableUpdateLastLoginTime: true
      enableRequestExtraAttributes: true
      enableUpdateLegacyPasswords: true
      properties:
        dataSource.cachePrepStmts: true
        dataSource.prepStmtCacheSize: 250
        dataSource.prepStmtCacheSqlLimit: 2048

# --- Theme and skin ---

  skin:
    <<: *shared_skin_defaults
    baseUrl: '{{ web_base_url }}/{{ app_theme_name }}'
    termsUrl: '{{ app_theme_custom_url }}'
    headerFooterUrl: '{{ web_base_url }}/{{ app_theme_name }}/'
    favIconBaseUrl: '{{ web_base_url }}/{{ app_theme_name }}/img/'
    loginBrandUrl: '{{ web_base_url }}/{{ app_theme_name }}/img/brand-logo.png'
    loginLogo: '{{ web_base_url }}/{{ app_theme_name }}/img/brand-logo.png'
    bieBaseUrl: '{{ app_theme_custom_url }}'
    bieSearchPath: '/{{ app_theme_name }}/custom_link.html'
    userDetailsUrl: '{{ web_base_url }}/{{ app_userdetails_name }}'
    resetPasswordUrl: '{{ web_base_url }}/{{ app_userdetails_name }}/registration/forgottenPassword'
    createAccountUrl: '{{ web_base_url }}/{{ app_userdetails_name }}/registration/createAccount'
    orgShortName: '[Org Name Short] [Proj Name Short]'
    orgLongName: '[Org Name Long] [Proj Name Long]'
    orgNameKey: 'org-name-code'
    loginFormUserPass: true
    cacheDuration: PT30m # 1800000
    supportEmail: '[Org Support Email]'
    ui-version: 2

# --- Spring ---

spring:

  session:
    enabled: true
    store-type: mongodb
    mongo:
      collectionName: sessions_cas

  data:
    mongodb:
      <<: *common_spring_data_mongodb_properties