---
# settings
app_userdetails_name: 'app_userdetails'
app_userdetails_group: 'app'
app_userdetails_category: 'auth'
app_userdetails_builder: 'gradle'
app_userdetails_java: '11'
app_userdetails_ports:
  http: '{{ specified_ports.userdetails_http_port }}'
  debug: '{{ specified_ports.userdetails_debug_port }}'
app_userdetails_links:
  tests: 'build/reports/tests/'

# paths
app_userdetails_config_dir: '/data/userdetails/config'
app_userdetails_helper_path: '{{ ubuntu_profile_dir }}/03-helper-app-userdetails.sh'
app_userdetails_entry_nginx_path: '{{ nginx_conf_partial_path }}/{{ app_userdetails_name }}.conf'
app_userdetails_entry_html_path: '{{ web_partial_dir }}/{{ app_userdetails_name }}.html'
app_userdetails_systemd_service_path: '{{ systemd_services_dir }}/{{ app_userdetails_name }}.service'
app_userdetails_config_path: '{{ app_userdetails_config_dir }}/userdetails-config.yml'
app_userdetails_source_dir: '{{ guest_src_dir }}/userdetails'

# databases
app_userdetails_db_main_database: 'userdetails_main'
app_userdetails_db_main_username: 'userdetails_main'

app_userdetails_db_test_database: 'userdetails_test'
app_userdetails_db_test_username: 'userdetails_test'

app_userdetails_db_spring_data_database: 'userdetails_spring_data'
app_userdetails_db_spring_data_username: 'userdetails_spring_data'

# Settings that resemble production to test the built artifact.
app_userdetails_java_opts:
  - '-Djava.awt.headless=true'
  - '-XX:+UseG1GC'
  - '-Xms256m'
  - '-Xmx1g'
  - '-XX:ErrorFile={{ services_dir }}/{{ app_userdetails_name }}_hs_err_pid_%p.log'
  - '-Dlog4j2.formatMsgNoLookups=true'
  - '-Dlogging.config={{ logback_config_path }}'
  - '-Dspring.output.ansi.enabled=never'
  - '-Dfile.encoding=UTF-8'

app_userdetails_env_vars:
  - key: 'SPRING_CONFIG_LOCATION'
    value: 'file:{{ app_userdetails_config_path }}'
  - key: 'LOG4J_FORMAT_MSG_NO_LOOKUPS'
    value: 'true'
  - key: 'LOG_DIR'
    value: '{{ log_dir }}'
  - key: 'LOGGING_DIR'
    value: '{{ log_dir }}'
