---
# settings
app_userdetails_name: 'app_userdetails'
app_userdetails_group: 'app'
app_userdetails_category: 'auth'
app_userdetails_builder: 'gradle'
app_userdetails_java: '11'
app_userdetails_ports:
  debug: '{{ specified_ports.userdetails_debug_port }}'
  http: '{{ specified_ports.userdetails_http_port }}'
app_userdetails_links:
  tests: 'build/reports/tests/'

# paths
app_userdetails_config_dir: '/data/userdetails/config'
app_userdetails_helper_path: '{{ ubuntu_profile_dir }}/03-helper-app-userdetails.sh'
app_userdetails_entry_nginx_path: '{{ nginx_conf_partial_path }}/{{ app_userdetails_name }}.conf'
app_userdetails_entry_html_path: '{{ web_partial_dir }}/{{ app_userdetails_name }}.html'
app_userdetails_systemd_service_path: '{{ systemd_services_dir }}/{{ app_userdetails_name }}.service'
app_userdetails_config_path: '{{ app_userdetails_config_dir }}/userdetails-config.yml'
app_userdetails_source_dir: '{{ guest_src_dir }}/userdetails'

# databases
# userdetails uses the same mysql db as CAS

app_userdetails_db_spring_data_database: 'userdetails_spring_data'
app_userdetails_db_spring_data_username: 'userdetails_spring_data'

# Settings for running the app that resemble production.
app_userdetails_java_sys_props:
  - 'java.awt.headless=true'
  - 'log4j2.formatMsgNoLookups=true'
  - 'logging.config={{ logback_config_path }}'
  - 'spring.output.ansi.enabled=never'
  - 'file.encoding=UTF-8'

app_userdetails_java_jvm_opts:
  - 'XX:+UseG1GC'
  - 'Xms256m'
  - 'Xmx1g'
  - 'XX:ErrorFile={{ services_dir }}/{{ app_userdetails_name }}_hs_err_pid_%p.log'

app_userdetails_env_vars:
  - key: 'SPRING_CONFIG_LOCATION'
    value: 'file:{{ app_userdetails_config_path }}'
  - key: 'LOG4J_FORMAT_MSG_NO_LOOKUPS'
    value: 'true'
