
# -- Shared reference blocks ---

shared_datasource_mysql_defaults: &shared_datasource_mysql_defaults
  driverClassName: 'com.mysql.cj.jdbc.Driver'
  driver-class: 'com.mysql.cj.jdbc.Driver'
  dialect: 'org.hibernate.dialect.MySQL8Dialect'
  pooled: true
  jmxExport: true
  type: "com.zaxxer.hikari.HikariDataSource"
  properties:
    initialSize: 5
    maxActive: 50
    maxIdle: 25
    minIdle: 5
    maxWait: 10000
    minEvictableIdleTimeMillis: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: 'SELECT 1'
    jmxEnabled: true

shared_security_cas_defaults: &shared_security_cas_defaults
  readOnlyOfficerRole: 'ROLE_FC_READ_ONLY'
  alaAdminRole: 'ROLE_ADMIN'
  officerRole: 'ROLE_FC_OFFICER'
  adminRole: 'ROLE_FC_ADMIN'
  casServerName: '{{ web_base_url }}'
  casServerLoginUrl: '{{ web_base_url }}/{{ app_cas_name }}/login'
  casServerUrlPrefix: '{{ web_base_url }}/{{ app_cas_name }}'
  logoutUrl: '{{ web_base_url }}/{{ app_cas_name }}/logout'
  loginUrl: '{{ web_base_url }}/{{ app_cas_name }}/login'

# For theming, see the version of 'ala-boostrap3' that is used by each app.
# Then have a look at the page that matches the 'layout' setting.
# e.g. https://github.com/AtlasOfLivingAustralia/ala-bootstrap3/blob/4.1.0/grails-app/views/layouts/_main.gsp

shared_header_footer_defaults: &shared_header_footer_defaults
  baseURL: '{{ web_base_url }}/{{ app_theme_name }}'
  version: '2'
  excludeApplicationJs: true
  excludeBootstrapCss: true
  excludeAlaStylesCss: true
  excludeBootstrapJs: true

shared_skin_defaults: &shared_skin_defaults
  layout: "ala-main"
  fluidLayout: false
  orgNameLong: "{{ org_name_long }}"
  orgNameShort: "{{ org_name_short }}"
  orgSupportEmail: '{{ email_address }}'
  favicon: '{{ web_base_url }}/{{ app_theme_name }}/favicon.ico'
  homeUrl: '{{ web_base_url }}/{{ app_biocollect_name }}'
  authorName: '[Author Name]'

shared_grails_mail_defaults: &shared_grails_mail_defaults
  host: '{{ local_host }}'
  port: '{{ specified_ports.mail_service_smtp_port }}'
  username: ''
  password: ''
  poolSize: 1
  props:
    - 'mail.smtp.starttls.enable': 'false'
    - 'mail.smtp.starttls.required': 'false'
    - 'mail.smtp.port': '{{ specified_ports.mail_service_smtp_port }}'
    - 'mail.smtp.auth': 'false'
    - 'mail.smtp.ssl.protocols': 'TLSv1.2'

shared_cas_mongo_defaults: &shared_cas_mongo_defaults
  ssl-enabled: false
  host: '{{ web_base_host }}'
  port: {{ specified_ports.mongo_service_port }}
  authentication-database-name: '{{ mongo_service_auth_database }}'

shared_grails_config_defaults: &shared_grails_config_defaults
  mime:
    use:
      accept:
        header: true
    disable:
      accept:
        header:
          userAgents: []
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      # htmlcodec: use xml escaping instead of HTML4 escaping
      htmlcodec: xml
      codecs:
        # codecs.expression: escapes values inside ${}, default html
        expression: html
        # codecs.scriptlets: # escapes output from scriptlets in GSPs, default html
        scriptlets: html
        # codecs.taglib: escapes output from taglibs, default to none as taglibs specify their own encoding
        taglib: none
        # codecs.staticparts: escapes output from static template parts, default none
        staticparts: none
  databinding:
    convertEmptyStringsToNull: false
  cache:
    enabled: true
    clearAtStartup: false
    cacheManager: GrailsEhcacheCacheManager
    # The ehcache config needs to be specified by each app
    # ehcache:
      # ehcacheXmlLocation: 'classpath:*-ehcache.xml'
