---

- name: Generate secret for app_biocollect_oidc_client_id
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 30
    secret_gen_type: password_string
    secret_gen_name: app_biocollect_oidc_client_id
- name: Register app_biocollect_oidc_client_id
  ansible.builtin.set_fact:
    app_biocollect_oidc_client_id: '{{ secret_gen_value }}'

- name: Generate secret for app_biocollect_oidc_secret
  ansible.builtin.import_role:
    name: common_secret_generation
  vars:
    secret_gen_size: 30
    secret_gen_type: password_string
    secret_gen_name: app_biocollect_oidc_secret
- name: Register app_biocollect_oidc_secret
  ansible.builtin.set_fact:
    app_biocollect_oidc_secret: '{{ secret_gen_value }}'
