---
# settings
app_apikey_name: 'app_apikey'
app_apikey_group: 'app'
app_apikey_category: 'auth'
app_apikey_builder: 'gradle'
app_apikey_java: '11'
app_apikey_ports:
  http: '{{ specified_ports.apikey_http_port }}'
  debug: '{{ specified_ports.apikey_debug_port }}'
app_apikey_links:
  tests: 'build/reports/tests/'

# paths
app_apikey_config_dir: '/data/apikey/config'
app_apikey_helper_path: '{{ ubuntu_profile_dir }}/03-helper-app-apikey.sh'
app_apikey_entry_nginx_path: '{{ nginx_conf_partial_path }}/{{ app_apikey_name }}.conf'
app_apikey_entry_html_path: '{{ web_partial_dir }}/{{ app_apikey_name }}.html'
app_apikey_systemd_service_path: '{{ systemd_services_dir }}/{{ app_apikey_name }}.service'
app_apikey_config_path: '{{ app_apikey_config_dir }}/apikey-config.yml'
app_apikey_source_dir: '{{ guest_src_dir }}/apikey'

# databases
app_apikey_db_main_database: 'apikey_main'
app_apikey_db_main_username: 'apikey_main'

app_apikey_db_test_database: 'apikey_test'
app_apikey_db_test_username: 'apikey_test'

app_apikey_db_spring_data_database: 'apikey_spring_data'
app_apikey_db_spring_data_username: 'apikey_spring_data'

# Settings that resemble production to test the built artifact.
app_apikey_java_opts:
  - '-Djava.awt.headless=true'
  - '-XX:+UseG1GC'
  - '-Xms256m'
  - '-Xmx500m'
  - '-XX:ErrorFile={{ services_dir }}/{{ app_apikey_name }}_hs_err_pid_%p.log'
  - '-Dlog4j2.formatMsgNoLookups=true'
  - '-Dlogging.config={{ logback_config_path }}'

app_apikey_env_vars:
  - key: 'SPRING_CONFIG_LOCATION'
    value: 'file:{{ app_apikey_config_path }}'
  - key: 'LOG4J_FORMAT_MSG_NO_LOOKUPS'
    value: 'true'
  - key: 'LOG_DIR'
    value: '{{ log_dir }}'
