---
# settings
app_ecodata_name: 'app_ecodata'
app_ecodata_group: 'app'
app_ecodata_category: 'web'
app_ecodata_builder: 'gradle'
app_ecodata_java: '11'
app_ecodata_ports:
  debug: '{{ specified_ports.ecodata_debug_port }}'
  http: '{{ specified_ports.ecodata_http_port }}'
app_ecodata_links:
  tests: 'build/reports/tests/'

# paths
app_ecodata_config_dir: '/data/ecodata/config'
app_ecodata_helper_path: '{{ ubuntu_profile_dir }}/03-helper-app-ecodata.sh'
app_ecodata_entry_nginx_path: '{{ nginx_conf_partial_path }}/{{ app_ecodata_name }}.conf'
app_ecodata_entry_html_path: '{{ web_partial_dir }}/{{ app_ecodata_name }}.html'
app_ecodata_systemd_service_path: '{{ systemd_services_dir }}/{{ app_ecodata_name }}.service'
app_ecodata_config_path: '{{ app_ecodata_config_dir }}/ecodata-config.yml'
app_ecodata_source_dir: '{{ guest_src_dir }}/ecodata'

# databases
app_ecodata_db_main_database: 'ecodata_main'
app_ecodata_db_main_username: 'ecodata_main'

app_ecodata_db_test_database: 'ecodata_test'
app_ecodata_db_test_username: 'ecodata_test'

# Settings for running the app that resemble production.
app_ecodata_java_sys_props:
  - 'java.awt.headless=true'
  - 'log4j2.formatMsgNoLookups=true'
  - 'logging.config={{ logback_config_path }}'
  - 'spring.output.ansi.enabled=never'
  - 'file.encoding=UTF-8'

app_ecodata_java_jvm_opts:
  - 'XX:+UseG1GC'
  - 'Xms1g'
  - 'Xmx3g'
  - 'Xss256k'
  - 'XX:ErrorFile={{ services_dir }}/{{ app_ecodata_name }}_hs_err_pid_%p.log'

app_ecodata_env_vars:
  - key: 'SPRING_CONFIG_LOCATION'
    value: 'file:{{ app_ecodata_source_dir }}/grails-app/conf/application.groovy,file:{{ app_ecodata_config_path }}'
  - key: 'LOG4J_FORMAT_MSG_NO_LOOKUPS'
    value: 'true'

app_ecodata_hub_default_id: "a2dffa51-e1d0-4c0f-a934-035c9b463c5a"
app_ecodata_hub_default_defs:
  - hubId: '{{ app_ecodata_hub_default_id }}'
    title: "Default"
    skin: "bs4"
    urlPath: "default"
    availableFacets: [
        "isExternal",
        "status",
        "organisationFacet",
        "associatedProgramFacet",
        "associatedSubProgramFacet",
        "mainThemeFacet",
        "stateFacet",
        "nrmFacet",
        "lgaFacet",
        "mvgFacet",
        "ibraFacet",
        "imcra4_pbFacet",
        "otherFacet",
        "gerSubRegionFacet",
        "electFacet"
      ]
    adminFacets: [
      "electFacet"
    ]
    availableMapFacets: [
      "status",
      "organisationFacet",
      "associatedProgramFacet",
      "associatedSubProgramFacet",
      "stateFacet",
      "nrmFacet",
      "lgaFacet",
      "mvgFacet",
      "ibraFacet",
      "imcra4_pbFacet",
      "electFacet"
    ]
