---

- name: Create directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: 'directory'
    owner: 'vagrant'
    group: 'vagrant'
    mode: 'u=rwx,g=rx,o=rx'
  loop:
    - '{{ app_theme_html_dir }}'
    - '{{ app_theme_html_dir }}/img'
    - '{{ app_theme_html_dir }}/js'
    - '{{ app_theme_html_dir }}/css'

- name: Template the nginx conf
  ansible.builtin.template:
    src: 'nginx-theme.conf'
    dest: '{{ app_theme_entry_nginx_path }}'
    force: true
    backup: false
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=r,o=r'

- name: Template the nginx html
  ansible.builtin.template:
    src: 'entry-index.html'
    dest: '{{ app_theme_entry_html_path }}'
    force: true
    backup: false
    owner: 'vagrant'
    group: 'vagrant'
    mode: 'u=rw,g=r,o=r'
  vars:
    entry_group: '{{ app_theme_group }}'
    entry_category: '{{ app_theme_category }}'
    entry_name: '{{ app_theme_name }}'
    entry_ports: '{{ app_theme_ports }}'
    entry_links: '{{ app_theme_links }}'

- name: Template the theme html files
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '{{ app_theme_html_dir }}/{{ item }}'
    force: true
    backup: false
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=r,o=r'
  loop:
    - 'banner.html'
    - 'footer.html'
    - 'head.html'
    - 'menu.html'
    - 'custom_link.html'

- name: Copy the theme image files
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ app_theme_html_dir }}/img/{{ item }}'
    force: true
    backup: false
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=r,o=r'
  loop:
    - 'android-icon-192x192.png'
    - 'android-chrome-192x192.png'
    - 'android-chrome-256x256.png'
    - 'apple-touch-icon.png'
    - 'brand-logo.png'
    - 'browserconfig.xml'
    - 'favicon.ico'
    - 'favicon.png'
    - 'favicon-16x16.png'
    - 'favicon-32x32.png'
    - 'mstile-150x150.png'
    - 'safari-pinned-tab.svg'
    - 'site.webmanifest'

- name: Copy the theme js files
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ app_theme_html_dir }}/js/{{ item }}'
    force: true
    backup: false
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=r,o=r'
  loop:
    - 'bootstrap.min.js'
    - 'application.js'

- name: Copy the theme css files
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ app_theme_html_dir }}/css/{{ item }}'
    force: true
    backup: false
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=r,o=r'
  loop:
    - 'ala-styles.css'
    - 'bootstrap.min.css'
